@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tictim.ceu.trait.energystorage;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;